env:
  global:
    - COVERALLS_REPO_TOKEN=cZ210SvbmfZwTGuJtOZtSk1ijoID9me5T
language: elixir
notifications:
  email:
    recipients:
      - carlos@carloslage.net
matrix:
  include:
    - elixir: "1.10"
      otp_release: "21.0"
    - elixir: "1.10"
      otp_release: "22.0"
    - elixir: "1.10"
      otp_release: "23.0"
    - elixir: "1.11"
      otp_release: "21.0"
    - elixir: "1.11"
      otp_release: "22.0"
    - elixir: "1.11"
      otp_release: "23.0"
    - elixir: "1.12"
      otp_release: "23.0"
script:
  - mix test
after_script:
  - mix coveralls.travis --pro
